{% set name = "ptufile" %}
{% set version = "2024.12.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptufile-{{ version }}.tar.gz
  sha256: bee8a1fdc1cca604d8d75a08b9c2e80aaf1a419ff385f4ddb80b0111e0d8488e

build:
  skip: true  # [py<310]
  entry_points:
    - ptufile = ptufile.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.11                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=68
    - numpy
    - cython >=3.0.11
    - pip
  run:
    - python
    - xarray >=2023.4.0
    - tifffile >=2024.8.30

test:
  imports:
    - ptufile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.cgohlke.com
  summary: Read and write PicoQuant PTU files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/ptufile

extra:
  recipe-maintainers:
    - cgohlke
