{% set name = "ptufile" %}
{% set version = "2025.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptufile-{{ version }}.tar.gz
  sha256: dc72d2eb984b4bb75763fbb5ed4b1b3fe4b5b12409d47862f5f6b1b0ec7282bd

build:
  skip: true  # [py<311]
  entry_points:
    - ptufile = ptufile.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.2                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=68
    - numpy
    - cython >=3.1.2
    - pip
  run:
    - python
    - xarray >=2023.4.0
    - tifffile >=2024.8.30

test:
  imports:
    - ptufile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.cgohlke.com
  summary: Read and write PicoQuant PTU files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/ptufile

extra:
  recipe-maintainers:
    - cgohlke
